<?php

namespace AppBundle\Repository;

/**
 * AffiliateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliateRepository extends \Doctrine\ORM\EntityRepository
{
}
